### ISSUE TITLE
请问npm install 后，run the tests 具体步骤是怎么做的？ 我运行不了

### ISSUE THREAD

**Issue by RylaiCrest** [HoverBaum/test-freemarker-variables#1]

**Comment by HoverBaum** [comment]
Should be:

```
node test.js
node test2.js
```

Hope that helps. I haven't looked at this for years and am also no longer concerned with freemarker at all. Still happy if this is of use 😊

**Comment by HoverBaum** [comment]
Closing, to keep things clean.
I hope the above was helpful, feel free to reach out or re-open for questions.
